allowBuilds:
  '@mongodb-js/zstd': false
  '@prisma/engines': true
  esbuild: true
  node-liblzma: false
  prisma: true
  unrs-resolver: false
overrides:
  deepmerge-ts: 8.0.2
  fast-uri: 3.1.6
  js-yaml: 4.3.2
  mysql2: 3.24.4
minimumReleaseAgeExclude:
  - eve@0.36.0
  - '@next/env@16.3.6'
  - '@next/swc-darwin-arm64@16.3.6'
  - '@next/swc-darwin-x64@16.3.6'
  - '@next/swc-linux-arm64-gnu@16.3.6'
  - '@next/swc-linux-arm64-musl@16.3.6'
  - '@next/swc-linux-x64-gnu@16.3.6'
  - '@next/swc-linux-x64-musl@16.3.6'
  - '@next/swc-win32-arm64-msvc@16.3.6'
  - '@next/swc-win32-x64-msvc@16.3.6'
  - next@16.3.6
  - '@next/eslint-plugin-next@16.3.6'
  - eslint-config-next@16.3.6
